CREATE TABLE UZYTKOWNICY(
ID INT GENERATED ALWAYS AS IDENTITY,
IMIE varchar(20) NOT NULL,
NAZWISKO varchar(30) NOT NULL,
EMAIL varchar(30) NOT NULL,
LOGIN varchar(30) NOT NULL,
HASLO varchar(30) NOT NULL,
DATA_ZALOZENIA TIMESTAMP,
OST_ZAL TIMESTAMP,
OST_WYL TIMESTAMP,
BLEDNE_HASLO INT,
DATA_BL_LOG TIMESTAMP,
UNIQUE(LOGIN),
UNIQUE(EMAIL),
CONSTRAINT id_uzytkownika PRIMARY KEY (id)
);


select * from uzytkownicy;

delete from uzytkownicy;

commit;